### ISSUE TITLE
sdptool add returned 255

### ISSUE THREAD

**Issue by mike-lt** [nccgroup/nOBEX#8]
Hi, 

I'm using this library on ubuntu 18.04. I tried pbapclient.py and mapclient.py and they work well. 
I tried hfpclient.py but I'm having this error
"sdptool add returned 255" on file bluez_helper.py line 92
when this line on hfpclient.py is called
bluez_helper.advertise_service('hf', port)

**Comment by sultanqasim** [comment]
It's failing here
https://github.com/nccgroup/nOBEX/blob/master/nOBEX/bluez_helper.py#L88

You can try running the command manually and observe the result: `sdptool add hf --channel=23 hf` (pick an unused channel number)

The hands free profile is a bit screwed up in that usually the client accepts connections from the server (audio gateway), instead of the server accepting connections from clients. The spec is vague on who should establish the connection, but it usually happens in the reverse direction I described. This is why the client tries advertising itself as a handsfree device accepting connections from Audio Gateway devices (phones).

Did you enable compat mode in bluetoothd by editing the systemd ExecStart line?

**Comment by mike-lt** [comment]
Hi, 

Compat mode was not enabled. I enabled it now but I'm having the same error.
I tried the following command by using the channels from 1 to 31 but I keep having as result 255 command not found.
`sdptool add --channel=[channel_number] HF`

**Comment by sultanqasim** [comment]
Which phone do you have?

**Comment by mike-lt** [comment]
I have a MI a2 lite
